# Generated by Django 6.0.2 on 2026-02-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='second_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
